FROM pravsingh/hygieia-sonar-codequality-collector

ENV MONGO_PORT tcp://devops-hygieiadb:27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE hygieia

ENV MONGODB_HOST devops-hygieiadb

ENV MONGODB_PORT 27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME admin

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD zaq12wsx

ENV SONAR_CRON 0 0/5 * * * *

ENV SONAR_URL http://devops-sonarqube:9000

ENV SONAR_USERNAME devopsadmin

ENV SONAR_PASSWORD zaq12wsx

ENV SONAR_VERSION 6
